site_name: EnviroTyping Model
site_description: EnviroTyping Model 
repo_url: https://github.com/
theme: readthedocs
pages:
-Home: index.md
	-‘Introduction to EnviroTyping Project’: intro_envirotypingModel.md
-Workflow:
	-‘Insight Maker Tutorial’: InsightMakerTutorial.md
	-‘Purpose’: Purpose.md
	-‘Running The Simulation’: RunningTheSimulation.md
	-'Modifying The Variables':ModifyingTheVariables.md
	-'Generating and Reading Data':GeneratingAndReadingData.md
	-'Wrap-up': WrapUp.md
	-'Helpful Vocabulary': Vocab.md

-Tutorials:
	 
