site_name: EnviroTyping Model
site_description: EnviroTyping Model 
repo_url: https://github.com/
theme: readthedocs
pages:
-Home: index.md
	-‘Introduction to EnviroTyping Project’: intro_envirotypingModel.md
-Workflow:
	-‘Getting Started’: GettingStarted.md
	-‘Variables and vocabulary’: Variables_Vocab.md
	-‘Running the simulation’: RunningSimulation.md

-Tutorials:
	 
